# ========================================= #
#  YAWL (Yet Another Whitelist Plugin)     #
# ========================================= #

[settings]
# Включить или выключить вайтлист. Если false, плагин никого не будет кикать.
enabled = true

[messages]
# Сообщение при кике. Поддерживает MiniMessage: <red>, <green>, <bold>, <hover:text> и т.д.
kick-message = "<red>Вы не в белом списке этого сервера!"

# Используйте плейсхолдеры в формате <player>, <count>, <players>
player-added = "<gray>Игрок <green><player></green> был добавлен в белый список."
player-already-exists = "<gray>Игрок <yellow><player></yellow> уже находится в белом списке."
player-removed = "<gray>Игрок <red><player></red> был удален из белого списка."
player-not-found = "<gray>Игрока <yellow><player></yellow> нет в белом списке."
list-header = "<gold>Игроки в белом списке (<count>):</gold><white> <players>"
list-empty = "<yellow>Белый список пуст."
no-permission = "<red>У вас нет прав для использования этой команды."